### ISSUE TITLE
Indeterminism in CT tests of apps/sse

### ISSUE THREAD

**Issue by lucafavatellawork** [opensparkl/sse_core#56]
While validating PR https://github.com/opensparkl/sse_core/pull/54 I noticed that a CI build failed once for apparently no reason. The failing CI build is [this](https://travis-ci.com/opensparkl/sse_core/builds/140585766).

This ticket tracks reviewing CT tests in apps/sse for determinism.

**Comment by jacobythwaites** [comment]
Noted. Let's keep an eye on these cases.

**Comment by lucafavatellawork** [comment]
Similar symptom in https://travis-ci.com/opensparkl/sse_core/builds/140839895

**Comment by lucafavatellawork** [comment]
Testing upgrade to OTP 21(+), I noticed the a CT test in apps/sse was failing almost always. See [failure on CI](https://travis-ci.com/opensparkl/sse_core/jobs/281597945). PR #28 - not merged yet - has [a test stability fix](https://github.com/opensparkl/sse_core/pull/28/commits/8b6feaa7276d4f1f91a6950b7cf57277d9bda65a).

**Comment by lucafavatellawork** [comment]
PR #28 merged - with a test stability fix. Closing this.
