### ISSUE TITLE
Client cert should not require a special user provider, nor a cookie session

### ISSUE THREAD

**Issue by jacobythwaites** [opensparkl/sse_core#67]
The use of a client certificate requires the user record to have `provider=sparkl_cert`. The user also needs to create a cookie session by invoking login.

The following changes should be made:

1. Allow any user to download their client certificate, protected by the password on the account.
2. Remove the need for a cookie session on client-cert connections.

**Comment by lucafavatellawork** [comment]
@jacobythwaites I expect this shall be closed now that https://github.com/opensparkl/sse_core/pull/68 is merged.
