### ISSUE TITLE
Potential memory leak in usage of xmerl

### ISSUE THREAD

**Issue by lucafavatellawork** [opensparkl/sse_core#79]
OTP xmerl uses atoms for representing some XML items. Review its usage so not to leak memory.

**Comment by jacobythwaites** [comment]
The xmerl sax parser does not generate atoms for local names of elements or attributes. We use this to generate the erlang structs in the import pipeline, which are processed by prog_change into the mnesia database.

**Comment by lucafavatellawork** [comment]
> The xmerl sax parser does not generate atoms for local names of elements or attributes.

👌

I double checked this on the codebase of PR #95 - now merged to master - by running the tests (sse_cli, eunit, ct) with an assertion on the number of atoms before and after invocations of `xmerl_sax_parser:stream` and `xmerl_sax_parser:file`. In order to make the number of atoms returned by `erlang:system_info(atom_count)` stable during ct tests, I had to:
- Add preceding line `ok = code:ensure_modules_loaded([erl_bits, eval_bits, io_lib_pretty])` (the need of this can be observed by starting `erl` then shortly after running `erlang:system_info(atom_count)` then running same command a few seconds later - noticing increased count).
- Add preceding line `_ = try xmerl_sax_parser:stream(<<"<elem/>">>, [{event_fun, fun event_/3}, {event_state, #?STATE{}}]) catch _:_ -> ok end` - for xmerl-specific atoms.
- Manually instantiating atoms `['Argument__2','Argument__1','Argument__4', 'Argument__3']` (by exporting a function returning these.)

For listing the atoms (so identify the source of missing atoms) I used the trick `binary_to_term(<<131,75,N:24>>)` described in https://stackoverflow.com/questions/13480462/can-i-get-a-list-of-all-currently-registered-atoms 
- (I listed atoms by using `AtomCount0 = erlang:system_info(atom_count)` then `Atoms0 = [binary_to_term(<<131,75,N:24>>) || N <- lists:seq(0, AtomCount0 - 1)]`.)
