### ISSUE TITLE
Lifecycle of temporary files

### ISSUE THREAD

**Issue by lucafavatellawork** [opensparkl/sse_core#87]
I [identified](https://github.com/opensparkl/sse_core/pull/82#pullrequestreview-356879017) this concern in PR #82 - that is not yet merged.

The application creates temporary files (see modules `sse_cfg_upload_yapp`, `sse_cfg_href`, `sse_cfg_transform`). Once not used any longer, the temporary files are not deleted explicitly by the application - neither in success or error paths - [expecting the OS to delete them](https://github.com/opensparkl/sse_core/pull/82#discussion_r378166317). This raises the following questions:
- If the OS is to delete temporary files, this is an OS configuration that shall be documented for the operator and implemented in recommended deployment(s) (Docker?, deb?).
- If the OS is to delete temporary files, considering that the application (Erlang VM) closes the file descriptors before still using the temporary file by path name, how does the OS know which files are safe to delete without disrupting the application?

**Comment by jacobythwaites** [comment]
I think the app should be responsible for deleting its own temporary files, which we clearly do not do at the moment. I will open a branch and draft PR for this.

**Comment by jacobythwaites** [comment]
Fixed by #95
